### ISSUE TITLE
Spacing not accounting for sibling spouse

### ISSUE THREAD

**Issue by nichiang** [SanichKotikov/relatives-tree#11]
Hi, I'm seeing an issue where the spacing generated doesn't seem to be accounting for a sibling's spouse:

![family_tree](https://user-images.githubusercontent.com/8085790/127730706-cdaedcf5-4a42-4209-b785-27cb3eff8713.png)

**Comment by SanichKotikov** [comment]
Hi. Please, share the data to reproduce the issue.

**Comment by nichiang** [comment]
https://gist.github.com/nichiang/6e34513f069ef1340f536ef938b15b7a

It seems to have been due to a misconfigured root node on my part. Setting it to 957875050 yields the layout in the screenshot above, while setting it to -306296563 (the proper root node) lays things out correctly.

**Comment by SanichKotikov** [comment]
Ok, thx. I'll check when I'll have some time.

**Comment by SanichKotikov** [comment]
Fixed and published (v3.0.2)
