### ISSUE TITLE
Spouses from different generations are duplicated

### ISSUE THREAD

**Issue by Zowiezo101** [SanichKotikov/relatives-tree#13]
I'm using this library for a complicated family tree and I noticed it's having an issue with spouses that are from different generations. It's duplicating everything on both spouses instead of one single tree..

I've attached an image that shows what I mean, and the following link is a Google drive link to the json example data for spouses from different generations: https://drive.google.com/file/d/13_lfSDgRm5Q4OB__wGjt-K4uPJJbXyiQ/view?usp=sharing

![2021-10-05](https://user-images.githubusercontent.com/91847374/136017039-c1375bc7-b39c-494a-bdb4-b995a23c5b4e.png)

I'm not sure it's actually an issue or that I'm doing something wrong, but won't hurt to ask the creator ;).

**Comment by Zowiezo101** [comment]
My appologies, it's not only for spouses from different generations, but also on the same generation.

**Comment by SanichKotikov** [comment]
Hi. This library does not support circular relations.
