### ISSUE TITLE
Wrong shift family when building the tree in the parent direction

### ISSUE THREAD

**Issue by ialse** [SanichKotikov/relatives-tree#16]
There is a problem when building the tree in the parent direction. Starting from the 3rd generation, the family on the right does not move to the right.

Previous versions of the library did not have this problem.
Screenshot and link to codeSandbox

https://codesandbox.io/s/tree-3-1-0-wrong-in-parent-direction-jste1c?file=/src/wrong-parent-irection.json

Screenshot explanation: Fedor and Lena have 2 parents, but Fedor's parents moved to the left and ended up under other cards
![image](https://user-images.githubusercontent.com/66719870/154679965-49c21a03-8a03-437e-8ccf-73876d5839a7.png)

**Comment by SanichKotikov** [comment]
Fixed in v3.2.0
