### ISSUE TITLE
Overlaps 

### ISSUE THREAD

**Issue by wojciechkibitlewski** [SanichKotikov/relatives-tree#17]
I am having a small problem with a very elaborate tree. Sometimes a div from FamilyNode overlaps another div. (screens below)

![image](https://user-images.githubusercontent.com/105292367/177998616-5a76c8b0-f271-451b-adb4-71a82caf4866.png)
![image](https://user-images.githubusercontent.com/105292367/177998684-dadc75f4-51ca-4d16-8c01-387b6848d366.png)

Here the boxes have not shifted and intermingle - which is a mistake
![image](https://user-images.githubusercontent.com/105292367/177998761-82ccc4ec-e465-48de-999e-637e3ead1ec5.png)

Where can I look for a solution?
Regard
Wojtek

**Comment by SanichKotikov** [comment]
Hi. Thanks for report. As always you have at least two options:
- waiting for someone will try to fix this (if you will share the json file) :)
- trying to fix it by your self and create a PR

**Comment by wojciechkibitlewski** [comment]
https://github.com/wojciechkibitlewski/react-family-tree/blob/main/src/family.json

**Comment by wojciechkibitlewski** [comment]
I entered the JSON objects twice. Always - with this nodes layout  - the same error appears.

**Comment by wojciechkibitlewski** [comment]
I am inserting the nodes step by step.
The problem arises at level four.

![image](https://user-images.githubusercontent.com/105292367/178103107-fa63a97a-0ec2-43f7-bcef-6576a02cf7da.png)

**Comment by wojciechkibitlewski** [comment]
I see a problem on the third level, but I don't know what it is.
If the module "Monika Romanowska" is linked only to "Franciszek Grzeszczyk" - an error arises.
If I add another node 'married' to the module 'Monika Romanowska' - everything is ok.
The JSON looks correct.

![image](https://user-images.githubusercontent.com/105292367/178105852-af7a776c-82ab-4e6f-aeb1-4e1e200f4cb4.png)
![image](https://user-images.githubusercontent.com/105292367/178105870-c9d6b4fa-b07a-4be9-bcf2-473e7c206d6f.png)

**Comment by SanichKotikov** [comment]
Please check that you are using `relatives-tree v3.1.0`

**Comment by wojciechkibitlewski** [comment]
I used react-family-tree...
ok, now I have corrected the dependencies and it works.
thx
