### ISSUE TITLE
Connector position failure in rare cases.

### ISSUE THREAD

**Issue by mitu-lv** [SanichKotikov/relatives-tree#6]
![graph](https://user-images.githubusercontent.com/712868/96994458-6c56a600-1535-11eb-849f-6d740823ae8c.png)
Tried it with really large set of nodes, connectors at one only one point failed to draw correctly.
682 and 78 are children of 684 and 685. 684 however has two spouses 685 and 76.

[big-sample.zip](https://github.com/SanichKotikov/relatives-tree/files/5428961/big-sample.zip)

Tried it with sample code from this node
`const data: { [key: string]: any[] } = {
  '285': bigSample,
};`

Maybe author has an idea what would be wrong with data?
Or maybe it is a bug?

**Comment by SanichKotikov** [comment]
Looks like a bug. I will look into.

**Comment by SanichKotikov** [comment]
Published v2.1.0. @mitu-lv can you check it?

**Comment by mitu-lv** [comment]
Sure @SanichKotikov!

**Comment by mitu-lv** [comment]
![image](https://user-images.githubusercontent.com/712868/97106650-b6719000-16cb-11eb-93c0-6e732775dd1e.png)
That issue is fixed now, but the beginning of example is drawn out of canvas :(

**Comment by SanichKotikov** [comment]
> That issue is fixed now

Nice! Thanks.

> but the beginning of example is drawn out of canvas :(
> First node that is drawn is not the left most in example.

This is a browser's limitation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#Maximum_canvas_size
